spring:
  application:
    name: e-reader
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/e-reader
    username: postgres
    password: postgres
  messages:
    basename: i18n/messages
    encoding: ISO-8859-1
logging:
  level:
    sql: debug

token:
  access:
    secret: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
    duration: 2h

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-southeast-1
    endpointUrl: https://s3.ap-southeast-1.amazonaws.com

application:
  bucket:
    name: uploadfileimage
