spring:
  application:
    name: e-reader
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/e-reader
    username: postgres
    password: postgres
logging:
  level:
    sql: debug
