spring:
  application:
    name: e-reader
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/e-reader
    username: postgres
    password: postgres

  messages:
    basename: i18n/messages
    encoding: UTF-8
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  freemarker:
    template-loader-path: classpath:/templates

logging:
  level:
    sql: debug

token:
  access:
    secret: ${TOKEN_ACCESS_SECRET}
    duration: 2h

cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
    region:
      static: ap-southeast-1
    endpointUrl: https://s3.ap-southeast-1.amazonaws.com

google:
  client:
    id: ${GOOGLE_CLIENT_ID}

application:
  bucket:
    name: uploadfileimage
  client:
    url:
      http://localhost:5173/#
  stripe:
    secret-key: ${STRIPE_SECRET_KEY}


user-admin:
  email: test@gmail.com
  password: 123456
